export const LOGIN = "LOGIN_REQUEST"
export const LOGOUT = "LOGOUT_REQUEST"
export const REGISTER = "REGISTER_REQUEST"

export const enum usersActionTypes{
    LOGIN = "LOGIN_REQUEST",
    LOGOUT = "LOGOUT_REQUEST",
    REGISTER = "REGISTER_REQUEST",
    SET_NEW_LOGGED_USER = "SET_NEW_LOGGED_USER",
    SET_NEW_ACCESS_TOKEN = "SET_NEW_ACCESS_TOKEN"
}