

export const GET_INITIAL_STOCK = "GET_INITIAL_STOCK",
             GET_SYMBOLS = "GET_SYMBOLS",
             UPDATE_CURRENT_STOCKS = "UPDATE_CURRENT_STOCKS",
             GET_STOCK_DATA = "GET_STOCK_DATA",
             UPDATE_SYMBOL_LIST = "UPDATE_SYMBOL_LIST",
             RENEW_STOCK_API_REQUEST_SLOTS = "RENEW_STOCK_API_REQUEST_SLOTS",
             EARLIEST_STOCK_API_REQUEST_COOLDOWN_TIME_EXPIRED = "EARLIEST_STOCK_API_REQUEST_COOLDOWN_TIME_EXPIRED"