

export const GET_INITIAL_STOCK = "GET_INITIAL_STOCK",
             GET_SYMBOLS = "GET_SYMBOLS",
             UPDATE_CURRENT_STOCKS = "UPDATE_CURRENT_STOCKS",
             GET_DATA_FOR_A_STOCK = "GET_DATA_FOR_A_STOCK",
             UPDATE_SYMBOL_LIST = "UPDATE_SYMBOL_LIST"