package utility;
	public enum functionTypes{
		TIME_SERIES_INTRADAY,
		TIME_SERIES_DAILY,
		TIME_SERIES_WEEKLY,
		TIME_SERIES_WEEKLY_ADJUSTED,
		TIME_SERIES_MONTHLY,
		TIME_SERIES_MONTHLY_ADJUSTED,
	}
